name: Playwright UI Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
    - name: Checkout tests repository
      uses: actions/checkout@v4

    - name: Checkout Cypress RWA application
      uses: actions/checkout@v4
      with:
        repository: 'cypress-io/cypress-realworld-app'
        path: 'app-source'

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: 'npm'

    - name: Install Test Framework Dependencies
      run: npm ci

    - name: Install Application Dependencies
      run: |
        cd app-source
        corepack enable
        yarn install

    - name: Run Playwright tests
      run: npx playwright test
      env:
        PLAYWRIGHT_CI_COMMAND: 'cd app-source && yarn dev'
